[package]
name = "xplane_udp"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
log = "0.4.22"

[dependencies.env_logger]
version = "0.11.5"
optional = true

[features]
default = []
examples = ["env_logger"]